import "./globals.css";
import "../../node_modules/bootstrap/dist/css/bootstrap.min.css";

export const metadata = {
    title: "Tooltabs",
    description: "Generated by Next.js",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body suppressHydrationWarning={true}>{children}</body>
        </html>
    );
}
